project:
  type: website
  output-dir: docs

website:
  open-graph: true
  title: "abiburns.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: db project.qmd
        text: Database Project
      - href: dvz project.qmd
        text: Data Visualization Project
      - text: Knowledge Mining
        menu:
          - href: "Burns_Proposal.pdf"
            text: Research Proposal
          - href: assignment1.qmd
            text: Assignment 1
          - href: assignment2.qmd
            text: Assignment 2
          - href: assignment3.qmd
            text: Assignment 3
          - href: assignment4.qmd
            text: Assignment 4

body-footer:
  To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
      
format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

