project:
  type: website
  output-dir: docs

website:
  open-graph: true
  title: "abiburns.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "Burns_Resume202401.pdf"
        target: _blank
        text: Resume
      - href: "https://abiburns.shinyapps.io/DARTweekday"
        target: _blank
        text: Database Project
      - href: "Group_finalproject_alt.html"
        target: _blank
        text: Data Visualization Project
      - text: Knowledge Mining
        menu:
          - href: pfc.qmd
            text: Class Notes
          - href: assignment2.qmd
            text: Assignment 2
          - href: assignment3.qmd
            text: Assignment 3
          - href: assignment4.qmd
            text: Assignment 4
          - href: assignment5.qmd
            text: Assignment 5
          - href: "Burns_Proposal.pdf"
            target: _blank
            text: Project Proposal
          - href: "https://abiburns.shinyapps.io/weather/"
            target: _blank
            text: Project Application
          - href: "Burns_Report.pdf"
            target: _blank
            text: Project Report

body-footer:
  To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
      
format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

