project:
  type: website
  output-dir: docs

website:
  open-graph: true
  title: "abiburns.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: db project.qmd
        text: Database Project
      - href: dvz project.qmd
        text: Data Visualization Project
      - href: assignments.qmd
        text: KM Assignments

body-footer:
  To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
      
format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

