project:
  type: website
  output-dir: docs

website:
  title: "abiburns.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      - text: Assignments
        menu: 
          - Assignment1.qmd
          - Assignment2.qmd
      - href: project.qmd
        text: Project
      
format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

