project:
  type: website
  output-dir: docs

website:
  title: "abiburns.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      - text: Assignments
        menu: 
          - text: Assignment 1
            href: Assignment1.pdf
          - text: Assignment 2
            href: Assignment2.pdf
      - href: project.qmd
        text: Project
      
format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

