project:
  type: website
  output-dir: docs

website:
  title: "abiburns.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      - href: assignments.qmd
        text: Assignments
      - href: https://abiburns.shinyapps.io/DARTschedule/
        text: Project
      
format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

